package initcmd

import (
	"fmt"
	"os"
	"strings"
)

// Generate writes a pitstop.yaml file from the scan result.
func Generate(result *ScanResult, outputPath string, force bool) error {
	if !force {
		if _, err := os.Stat(outputPath); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite)", outputPath)
		}
	}

	content := renderYAML(result)
	return os.WriteFile(outputPath, []byte(content), 0644)
}

// renderYAML produces a human-readable pitstop.yaml with comments.
func renderYAML(r *ScanResult) string {
	var b strings.Builder

	b.WriteString("# Generated by pitstop init — 请根据实际情况修改\n")
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("project:\n"))
	b.WriteString(fmt.Sprintf("  name: %q\n\n", r.ProjectName))

	b.WriteString("services:\n")
	for _, svc := range r.Services {
		b.WriteString(fmt.Sprintf("  %s:\n", svc.Name))
		b.WriteString(fmt.Sprintf("    type: %s\n", svc.Type))
		if svc.Path != "" {
			b.WriteString(fmt.Sprintf("    path: %q\n", svc.Path))
		}
		b.WriteString(fmt.Sprintf("    command: %q\n", svc.Command))
		if svc.Port > 0 {
			b.WriteString(fmt.Sprintf("    port: %d\n", svc.Port))
		}
		if svc.HealthCheck != "" {
			b.WriteString(fmt.Sprintf("    health_check: %q\n", svc.HealthCheck))
		}
		b.WriteString("\n")
	}

	if len(r.Requirements) > 0 {
		b.WriteString("requirements:\n")
		// Output in a predictable order.
		keys := []string{"java", "maven", "node", "pnpm", "python"}
		for _, k := range keys {
			if v, ok := r.Requirements[k]; ok {
				b.WriteString(fmt.Sprintf("  %s: %q\n", k, v))
			}
		}
		// Output any remaining keys not in the predefined order.
		for k, v := range r.Requirements {
			if !contains(keys, k) {
				b.WriteString(fmt.Sprintf("  %s: %q\n", k, v))
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("logging:\n")
	b.WriteString("  dir: \"./logs\"\n")
	b.WriteString("  stdout: true\n")

	return b.String()
}

func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}
