package scriptgen

// ScriptData holds the template data for script generation.
type ScriptData struct {
	ProjectName string
	Services    []ServiceData
	OutputDir   string // directory for PID/log files
}

// ServiceData holds per-service template data.
type ServiceData struct {
	Name    string
	Cwd     string
	Command string
}

const startShTpl = `#!/bin/bash
# PitStop — {{.ProjectName}} — Start Script
# Generated by pitstop export

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PID_DIR="{{.OutputDir}}/.pids"
LOG_DIR="{{.OutputDir}}"

mkdir -p "$PID_DIR" "$LOG_DIR"

echo "🏁 Starting {{.ProjectName}}..."
echo ""

{{- range .Services}}
# --- {{.Name}} ---
echo "  Starting [{{.Name}}]..."
cd "$SCRIPT_DIR/{{.Cwd}}"
nohup {{.Command}} > "$LOG_DIR/{{.Name}}.log" 2>&1 &
echo $! > "$PID_DIR/{{.Name}}.pid"
echo "    PID: $(cat "$PID_DIR/{{.Name}}.pid") → $LOG_DIR/{{.Name}}.log"
{{end}}

echo ""
echo "All services started."
echo "Logs: $LOG_DIR"
echo "Run ./stop.sh to stop all services."
`

const stopShTpl = `#!/bin/bash
# PitStop — {{.ProjectName}} — Stop Script
# Generated by pitstop export

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PID_DIR="{{.OutputDir}}/.pids"

echo "Stopping {{.ProjectName}}..."

if [ ! -d "$PID_DIR" ]; then
  echo "No PID directory found. Services may not be running."
  exit 0
fi

stopped=0
for pidfile in "$PID_DIR"/*.pid; do
  [ -f "$pidfile" ] || continue
  name=$(basename "$pidfile" .pid)
  pid=$(cat "$pidfile")

  if kill -0 "$pid" 2>/dev/null; then
    echo "  Stopping [$name] (PID: $pid)..."
    kill "$pid" 2>/dev/null || true
    # Wait up to 10 seconds.
    for i in $(seq 1 20); do
      kill -0 "$pid" 2>/dev/null || break
      sleep 0.5
    done
    # Force kill if still alive.
    if kill -0 "$pid" 2>/dev/null; then
      echo "    Force killing [$name]..."
      kill -9 "$pid" 2>/dev/null || true
    fi
    stopped=$((stopped + 1))
  else
    echo "  [$name] (PID: $pid) already stopped."
  fi
  rm -f "$pidfile"
done

rmdir "$PID_DIR" 2>/dev/null || true

echo ""
echo "Stopped $stopped service(s)."
`

const startBatTpl = `@echo off
REM PitStop — {{.ProjectName}} — Start Script
REM Generated by pitstop export

setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
set "PID_DIR={{.OutputDir}}\\.pids"
set "LOG_DIR={{.OutputDir}}"

if not exist "%PID_DIR%" mkdir "%PID_DIR%"
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

echo Starting {{.ProjectName}}...
echo.

{{- range .Services}}
REM --- {{.Name}} ---
echo   Starting [{{.Name}}]...
cd /d "%SCRIPT_DIR%\\{{.Cwd}}"
start /b cmd /c "{{.Command}}" > "%LOG_DIR%\\{{.Name}}.log" 2>&1
echo !ERRORLEVEL! > "%PID_DIR%\\{{.Name}}.pid"
echo     PID: !ERRORLEVEL!
{{end}}

echo.
echo All services started.
echo Logs: %LOG_DIR%
echo Run stop.bat to stop all services.
`

const stopBatTpl = `@echo off
REM PitStop — {{.ProjectName}} — Stop Script
REM Generated by pitstop export

setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
set "PID_DIR={{.OutputDir}}\\.pids"

echo Stopping {{.ProjectName}}...

if not exist "%PID_DIR%" (
  echo No PID directory found. Services may not be running.
  exit /b 0
)

set stopped=0
for %%f in ("%PID_DIR%\\*.pid") do (
  set "name=%%~nf"
  set /p pid=<"%%f"

  echo   Stopping [!name!] (PID: !pid!)...
  taskkill /PID !pid! /T >nul 2>&1
  if !ERRORLEVEL! equ 0 (
    set /a stopped+=1
  ) else (
    echo     Already stopped.
  )
  del "%%f" >nul 2>&1
)

echo.
echo Stopped !stopped! service(s).
`
